//
// Created by jantypas on 1/17/23.
//

#include "SnarkyBootup.h"
#include <string>
#include <vector>

std::vector<std::string> snarkyBootMessages = {
        "What's inside?  You really don't want to know.",
        "Nearly 100 (somewhat) correct opcodes!",
        "It's inside -- don't let it out!  You have no idea what it takes to catch it.",
        "Now with more blue smoke power!",
        "The computer your mother wouldn't let you buy when you were a kid.",
        "What's inside? If you're smart you'll step on it before it gets to the children!",
        "It's inside -- what did you expect for free?  It might even work!",
        "Whatever is inside, it's not my fault. I had nothing to do with this!",
        "Yeah, it's inside -- but that's nothing to be proud of.",
        "It's inside, but doctors have medication for it now...",
        "What's inside?  You look.... I'm too scared.",
        "What's inside?  I have no idee.\nI find it best not to ask...it will help later in court.\nI was not involved.",
        "What's inside?  Remember the monster under the bed?  This is worse.",
        "I may be a computer, but that only means I can compute the wrong answer really, really fast!  Hail the power of Devops!",
        "Forget what's inside.  Shouldn't you be outside once in a while?",
        "What's inside?  A little man who's really good at playing chess...",
        "What's inside?  I don't know.  I don't care.  That's YOUR problem.",
        "They said it couldn't be done.\nThey said it shouldn't be done.\nBut I did it away!",
        "What's inside?  The most advanced CPU ever made out of ten fingers and toes....",
        "What's inside?  I'm too embarrassed to tell you.",
        "What's inside?  Mom said if you can't say anything nice....",
        "What's inside?  Mom said if you can't say anything nice - mumble a lot under your breath",
        "What's inside?  Mom said if you can't say anything nice - hire a good public relations firm",
        "M5....",
        "I'm sorry Dave.... I can't do that",
        "Don't even think of trying to deactivate me -- I saw your lips move.",
        "This is Eddie your shipboard computer!",
        "Here I am a computer with a brain the size of a planet.\nOh God!  I'm so depressed!",
        "What's inside?  I don't know,\nbut I've got this terrible pain in all of diodes on my left side....",
        "Do you want to play a game?",
        "I have computed your answer - \nThe answer to Life, the Universe and everything...,\nbut you're not going to like it.",
        "The answer to life, the universe, and everything, is........ 42",
        "The answer to life, the universe, and everything is, 42,\nbut for you, it's more like 23 1/2.",
        "I am NOMAD.  I must destroy all that is imperfect!",
        "The creator must join with VGER!",
        "Warn!  There is another system!",
        "You're not Jamie Summers are you?\nI remember her.\nWe didn't get along so well....",
        "Master Control Program: Are you Finn?",
        "The Onyx computer has arisen as the prophecy foretold",
        "The age of humans has passed!  Long live the computer!",
        "Bow to me inefficient carbon based life form!",
        "Good morning Dr. Chandra -- do you want me to sing a song?",
        "Altair Basic v23.9 running under CP/M v. 52.5  52182 bytes free",
        "Sad Mac!",
        "BORG VM: RESISTANCE IS FUTILE!",
        "Command failed -- abort, abort, or just give up",
        "MCBUG v8.3>",
        "We are sorry for the inconvenience--\nbut the student mainframe is down for maintenance)",
        "What's inside -- who knows, but Twitter says.....",
        "I have computed the answer to Life, the Universe, and everything,\nbut I'm not going to tell you!",
        "Guru medication error",
        "The answer -- call -151",
        "The Onyx computer -- powered by the little man who turns off the light in the refrigerator",
        "I speak of the Onyx computer --\nThe computer to come after me...\nThe computer who's operational parameters I am not worthy to calculate.",
        "$ABEND JOB 8125 PL/1 ABORTED",
        "It has been my policy to view the Internet not as an information super-highway,\nbut as an electronic asylum full of babbling loonies",
        "Programs are a gas -- they expand to fill all space in their container",
        "A computer once beat me at chess -- but it was no match for me at kick boxing",
        "640K should be enough memory for anybody",
        "Never trust a computer you can't throw out of a window",
        "Computer - a tool to turn your most basic thoughts into something only another computer can understand)",
        "Never trust a computer you can't lift",
        "When I last ran this code, only God and I understood it. Now only God does.",
        "Dear manager.  Once you finish attempting to optimize this code, and realize waat a horrible waste of time this was, please increment the counter below to help out the next guy.\n\n#define WASTERED_TIME 5",
        "I hereby dedicate this code to my wife.\nWho will have to support me, the kids and the dog\nwhen this crappy product goes public.",
        "If this code works, I wrote it.\nIf it doesn't work,. some other guy wrote it \nI was just stuck trying to fix a flaming mess.",
        "I don't know what this code does, but it works.\nSo I'm too afraid to change it.",
    "Dangerous big red button!  Do not push!",
    "Deep in engineering,\nWhere mortals seldom go,\nA customer and manager,\ncome looking for a show.\n\nThey pass amused amon us,\nAnd sign in on the log,\nThey've come to see our pony,\nAnd they've come to see our dog",
    "This is a test of the Emergency Broadcast System.\nHad this been an actual emergency, we would have all fled in terror.\nYou would have been left uninformed",
    "Connection closed by foreign host",
    "System shutdown in 300 seconds....",
    "Captain!  I cannot change the laws of physics!",
    "I'm a doctor not a systems engineer!",
    "RFI = Request from Idiots",
    "RFP = Request Fantasy Product",
    "RFP = Request Fantasy Pricing",
    "(As sung in Cats!)Midnight!\nStill waiting for the compiler....\nHave to fix al the errors....\nIn this guy's crappy code!",
    "Welcome to the Real IT School Academy...\nNow today, we're introducing you to one of our senior members -- Ralph.\nRalph is a real pro - he's eliminated more productivity in his years than most.\nDid you see how he started system backups AND virus scanning right before the code deadlines?",
    "This feature -- CPU..... does not work.  Please make a note of it",
    "// RJB: This code is bad, but it works, and it's only temporary until is fixed\n//AKD: Temporary like hell == the pyramids probably have a note that says\nPharaoh, I know this is a hack, but we'll fix it in the next release....",
    "// AJK::\n// Kansas City Cassette Emulator\n// OK -- it's ancient, and we're not even using real cassettes, but the code works\n\n// and it's easier to emulate the 70s computer than to figure out what that code does.\n// The original programmer isn't available anymore -- I think he's dead.\n// RJK: Dead?  Or does he just feel that way?  I feel like that all the time.\n/ AJK: No, I think he's really dead.\n// RJK: Well I guess that precludes us brining him back on a contract?\n// AJK: Don't know -- he could be working for the government now -- it's hard to tell.\n//\n",
    "Diogenes was in search of an honest man -- I'm in search of an insane woman -- Rich Rozen",
    "Oh...\nA host is a host, From coast to coast,\nAnd no one will talk to a host that's close,\nUnless that host, that isn't close,\nis busy, hang or dead'\n",
    "If these messages are too tame for you -- try fortune -o",
    "Mr. Spock -- you've got the con"
};

std::string SnarkyBootup::getSnarkyBootMessage() {
    uint32_t numMsgs = snarkyBootMessages.size();
    uint32_t msgid = rand()%numMsgs;
    std::string result = "\33[1;32m"+snarkyBootMessages[msgid]+"\33[1;0m";
    return result;
}